INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Rivers" and prenom like  "Aegor"), "Compagnie Dorée");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Aemon"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Aemon"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Targaryen" and prenom like  "Aemond"), "Verts");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Greyjoy" and prenom like  "Aeron"), "Dieu Noyé");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Aggo"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Thorne" and prenom like  "Alliser"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Anguy"), "Fraternité sans Bannières");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Armeca"), "Petyr Baelish");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Briseglace" and prenom like  "Arson"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Arthur"), "Qyburn");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Arthur"), "Varys");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Dayne" and prenom like  "Arthur"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Targaryen" and prenom like  "Baelor"), "Foi des Sept");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Selmy" and prenom like  "Barristan"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Paenymion" and prenom like  "Belicho"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Stark" and prenom like  "Benjen"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "de Torth" and prenom like  "Brienne"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "de Torth" and prenom like  "Brienne"), "Renly Baratheon");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Bronn"), "Jaime Lannister");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Bronn"), "Tyrion Lannister");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Bruni"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Bruni"), "Marcheurs Blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Dondarrion" and prenom like  "Béric"), "Fraternité sans Bannières");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Caleotte"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Camello"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Thenn" and prenom like  "Change-peau"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Thenn" and prenom like  "Change-peau"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Thenn" and prenom like  "Change-peau"), "Thenns");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Chella"), "Oreilles Noires");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Clarenzo"), "Oreilles Noires");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Clea"), "Oreilles Noires");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Cleon"), "Oreilles Noires");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Cohollo"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Cooper"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Stark" and prenom like  "Cregan"), "Noirs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Cressen"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Naharis" and prenom like  "Daario"), "Puînés");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Targaryen" and prenom like  "Daemon"), "Noirs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Mallister" and prenom like  "Denys"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Dalba" and prenom like  "Dim"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Dalba" and prenom like  "Dim"), "Jon Snow");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Dalba" and prenom like  "Dim"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Dolf"), "Freux");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Dongo"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Dongo"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Doreah"), "Xaro Xhoan Daxos");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "le Grand" and prenom like  "Duncan"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ebrose"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ebrose"), "Citadelle");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Tallett" and prenom like  "Eddison"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Fennesz"), "Mighdal");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Fermier"), "Mighdal");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Feuille"), "Enfants de la Forêt");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Frances"), "Qyburn");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Frances"), "Varys");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "abandonnée" and prenom like  "Gamine"), "Sans-Visage");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Gared"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Gendel"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Genna"), "Petyr Baelish");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Hightower" and prenom like  "Gerold"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ghita"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Gorne"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Moineau" and prenom like  "Grand"), "Foi des Sept");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Moineau" and prenom like  "Grand"), "Moineaux");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Moineau" and prenom like  "Grand"), "Foi Militante");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Clegane" and prenom like  "Gregor"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "mo Ullhor" and prenom like  "Greizhen"), "Astapor");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Grenn"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Guymon"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Gaunt" and prenom like  "Gwayne"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Haggo"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Hallyne"), "Guilde des Alchimistes");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Strickland" and prenom like  "Harry"), "Compagnie Dorée");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Helliweg"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "zo Loraq" and prenom like  "Hizdahr"), "Grands Maîtres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "zo Loraq" and prenom like  "Hizdahr"), "Meereen");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Flowers" and prenom like  "Jafer"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Flowers" and prenom like  "Jafer"), "Marcheurs Blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Lannister" and prenom like  "Jaime"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Slynt" and prenom like  "Janos"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "H'ghar" and prenom like  "Jaqen"), "Sans-Visage");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Rykker" and prenom like  "Jaremy"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "de Vieilles-Pierres" and prenom like  "Jenny"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Mormont" and prenom like  "Jeor"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Jhiqui"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Johnna"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Snow" and prenom like  "Jon"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Darry" and prenom like  "Jonothor"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Mormont" and prenom like  "Jorah"), "Varys");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Mormont" and prenom like  "Jorah"), "Compagnie Dorée");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Joramun"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kaeth"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Tanner" and prenom like  "Karl"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Karsi"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Karsi"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Karsi"), "Marcheurs blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kayla"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kayla"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kayla"), "Marcheurs blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kinvara"), "R'hllor");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kinvara"), "Temple Rouge de Volantis");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Kovarro"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "mo Nakloz" and prenom like  "Kraznys"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Lannister" and prenom like  "Lancel"), "Moineaux");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Lannister" and prenom like  "Lancel"), "Foi Militante");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Loboda"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Loboda"), "Thenns");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Loboda"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Locke"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Velaryon" and prenom like  "Lucerys"), "Noirs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Luwin"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Mar Tun" and prenom like  "Mag"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Maggy"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Magicien"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mago"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Rayder" and prenom like  "Mance"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Rayder" and prenom like  "Mance"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Moore" and prenom like  "Mandon"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Marei"), "Petyr Baelish");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Martha"), "Varys");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mero"), "Puînés");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Trant" and prenom like  "Meryn"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mhaegen"), "Petyr Baelish");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mighdal"), "Grands Maîtres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mighdal"), "Meereen");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mirelle"), "Petyr Baelish");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Maz Duur" and prenom like  "Mirri"), "Pâtre Suprême");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mordane"), "Foi des Sept");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Munkun"), "Citadelle");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mycah"), "Citadelle");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Omble" and prenom like  "Mycah"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mélisandre"), "Jon Snow");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Mélisandre"), "R'hllor");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Omble" and prenom like  "Ned"), "Marcheurs Blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Olly"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Orell"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Orell"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ornela"), "Dosh kaleen");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Yarwyck" and prenom like  "Othell"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Othor"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Othor"), "Marcheurs Blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "zo Pahl" and prenom like  "Oznak"), "Grands Maîtres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "zo Pahl" and prenom like  "Oznak"), "Meereen");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Payne" and prenom like  "Podrick"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Payne" and prenom like  "Podrick"), "Brienne de Torth");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Payne" and prenom like  "Podrick"), "Tyrion Lannister");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "du dosh" and prenom like  "Prophétesse"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Pree" and prenom like  "Pyat"), "Treize");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Pree" and prenom like  "Pyat"), "Conjurateurs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Pypar"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Qhono"), "Daenerys Targaryen");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Qhono"), "Moro");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Qhorin"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Qotho"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Quaithe"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Qyburn"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Rakharo"), "Drogo");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Rast"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Coq" and prenom like  "Rat"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ray"), "Foi des Sept");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "mo Eraz" and prenom like  "Razdal"), "Foi des Sept");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Targaryen" and prenom like  "Rhaenyra"), "Noirs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "de la" and prenom like  "Roi"), "Marcheurs Blancs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "de la" and prenom like  "Roi"), "Treize");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "des Épices" and prenom like  "Roi"), "Treize");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "du Cuivre" and prenom like  "Roi"), "Treize");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ros"), "Petyr Baelish");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ros"), "Varys");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Rossart"), "Guilde des Alchimistes");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Tarly" and prenom like  "Samwell"), "Ordre des Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Tarly" and prenom like  "Samwell"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Clegane" and prenom like  "Sandor"), "Fraternité sans Bannières");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Clegane" and prenom like  "Sandor"), "Garde Royale");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "des Os" and prenom like  "Seigneur"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Shagga"), "Freux");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Stiv"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Styr"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Styr"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Styr"), "Thenns");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Forel" and prenom like  "Syrio"), "Seigneur de la Mer");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Stark" and prenom like  "Talisa"), "Famille Maegyr");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Greyjoy" and prenom like  "Theon"), "otage");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Thoros"), "Fraternité sans Bannières");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Thoros"), "R'hllor");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Timett"), "Faces Brûlées");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Baratheon" and prenom like  "Tommen"), "Foi Militante");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Tormund"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Tormund"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Tormund"), "Jon Snow");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "d'Alluve" and prenom like  "Tristan"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Nestoris" and prenom like  "Tycho"), "Banque de Fer");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Unella"), "Foi des Sept");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Unella"), "Saintetés");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Unella"), "Foi Militante");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Vala"), "Fils de la Harpie");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Gris" and prenom like  "Ver"), "Immaculés");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Targaryen" and prenom like  "Viserys II"), "Noirs");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Wallen"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Royce" and prenom like  "Waymar"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Weyland"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Will"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Willa"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Wolkan"), "Mestres");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Weg Wun" and prenom like  "Wun"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Weg Wun" and prenom like  "Wun"), "Jon Snow");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "Xhoan Daxos" and prenom like  "Xaro"), "Treize");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "zo Qaggaz" and prenom like  "Yezzan"), "Bontés");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ygrid"), "Peuple libre");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ygrid"), "Jon Snow");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Ygrid"), "Mance Rayder");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Yoren"), "Garde de Nuit");
INSERT INTO Allegeance_camp (id_personnage, id) values ((select id_personnage from personnage where nom like "" and prenom like  "Zanrush"), "R'hllor");
