INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Chasse au Vautour", (select id_region from region where nom like "Marches de Dorne"),"An 37[1]","An 37[1]");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Chute du Roi de la Nuit", (select id_region from region where nom like "Fort Nox"),"An 37[1]","An 37[1]");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Conflit Au-delà du Mur", (select id_region from region where nom like "Au-delà du Mur"),"Vers l'an 280 (Peuple libre)[1]An 298 (intervention de la Garde de Nuit)","An 304");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Conflit Au-delà du Mur", (select id_region from region where nom like "Au-delà du Mur"),"Vers l'an 280 (Peuple libre)[1]An 298 (intervention de la Garde de Nuit)","An 304");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Conflit entre Forrester et Whitehill (A Telltale Games Series)", (select id_region from region where nom like "Le Nord"),"An 301","An 301");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Conquête de Dorne", (select id_region from region where nom like "Dorne"),"An 157","An 161");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Danse des Dragons", (select id_region from region where nom like "Dorne"),"An 157","An 161");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Danse des Dragons", (select id_region from region where nom like "Westeros"),"An 129","An 131");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Défi de Sombreval", (select id_region from region where nom like "Sombreval"),"An 129","An 131");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Grande Guerre", (select id_region from region where nom like "Sombreval"),"An 129","An 131");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Grande Guerre", (select id_region from region where nom like "Nord"),"An 304","An 305");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre de Gorne et Gendel", (select id_region from region where nom like "Don"),"An 304","An 305");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre de la Conquête", (select id_region from region where nom like "Westeros"),"An 2 (avant la Conquête)","An 1");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Guerre de la Conquête", (select id_region from region where nom like "Westeros"),"An 2 (avant la Conquête)","An 1");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Guerre de la Foi", (select id_region from region where nom like "Westeros"),"An 2 (avant la Conquête)","An 1");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre de la Foi", (select id_region from region where nom like "Sept Couronnes"),"An 41","An 48");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre de Mille Ans", (select id_region from region where nom like "Nord"),"An 41","An 48");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre des Cinq Rois", (select id_region from region where nom like "Westeros"),"An 298","An 300 (Phase I)An 302 (Phase II)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Guerre des Cinq Rois", (select id_region from region where nom like "Westeros"),"An 298","An 300 (Phase I)An 302 (Phase II)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre des Premiers Hommes et des Enfants de la Forêt", (select id_region from region where nom like "Westeros"),"12 000 (avant la Conquête)","10 000 (avant la Conquête)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre des Rois à Neuf Sous", (select id_region from region where nom like "Degrés de Pierre"),"An 259","An 259");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerre pour les Degrés de Pierre", (select id_region from region where nom like "Degrés de Pierre"),"An 106","An 115");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Guerres Ghiscaries", (select id_region from region where nom like "Péninsule valyrienne"),"6 000 (avant la Conquête)","5 000 (avant la Conquête)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Intrigues d'entre-deux guerres", (select id_region from region where nom like "Westeros"),"An 302","An 303 (À Port-Réal)An 304 (Au Nord)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Intrigues d'entre-deux guerres", (select id_region from region where nom like "Westeros"),"An 302","An 303 (À Port-Réal)An 304 (Au Nord)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Invasion de Westeros par Daenerys Targaryen", (select id_region from region where nom like "Westeros"),"An 304","An 305");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Invasion de Westeros par Daenerys Targaryen", (select id_region from region where nom like "Westeros"),"An 304","An 305");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Invasion des Andals", (select id_region from region where nom like "Westeros"),"6 000 (avant la Conquête)","4 000 (avant la Conquête)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Libération de la Baie des Serfs", (select id_region from region where nom like "Westeros"),"6 000 (avant la Conquête)","4 000 (avant la Conquête)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Libération de la Baie des Serfs", (select id_region from region where nom like "Baie des Serfs"),"An 300","An 303");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Longue Nuit", (select id_region from region where nom like "Westeros"),"8 000 (avant la Conquête)","8 000 (avant la Conquête)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Première Guerre Dornienne", (select id_region from region where nom like "Principauté de Dorne"),"An 4","An 13");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Rébellion de Robert", (select id_region from region where nom like "Westeros"),"An 280","An 281 (Port-Réal)An 282 (Peyredragon)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Rébellion de Robert", (select id_region from region where nom like "Westeros"),"An 280","An 281 (Port-Réal)An 282 (Peyredragon)");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Rébellion Feunoyr", (select id_region from region where nom like "Sept Couronnes"),"An 195","An 196");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Rébellion Feunoyr", (select id_region from region where nom like "Sept Couronnes"),"An 195","An 196");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Rébellion Greyjoy", (select id_region from region where nom like "Îles de Fer"),"An 289","An 289");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Catégorie:Rébellion Greyjoy", (select id_region from region where nom like "Îles de Fer"),"An 289","An 289");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Rébellion Reyne", (select id_region from region where nom like "Terres de l'Ouest"),"An 260","An 260");
INSERT INTO Guerre (nom, id_lieu, dirigeant,annee_deb , annee_fin) values ("Unification du Nord", (select id_region from region where nom like "Nord"),"8 000 (avant la Conquête)","6 000 (avant la Conquête)");
