INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Chasse au Vautour", (select id_region from region where nom like "Marches de Dorne"),"37","37");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Chute du Roi de la Nuit", (select id_region from region where nom like "Fort Nox"),"37","37");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Conflit Au-delà du Mur", (select id_region from region where nom like "Au-delà du Mur"),"298","304");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Conflit entre Forrester et Whitehill (A Telltale Games Series)", (select id_region from region where nom like "Le Nord"),"301","301");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Conquête de Dorne", (select id_region from region where nom like "Dorne"),"157","161");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Danse des Dragons", (select id_region from region where nom like "Westeros"),"129","131");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Défi de Sombreval", (select id_region from region where nom like "Sombreval"),"129","131");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Grande Guerre", (select id_region from region where nom like "Nord"),"304","305");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre de Gorne et Gendel", (select id_region from region where nom like "Don"),"304","305");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre de la Conquête", (select id_region from region where nom like "Westeros"),"-2","1");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre de la Foi", (select id_region from region where nom like "Sept Couronnes"),"41","48");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre de Mille Ans", (select id_region from region where nom like "Nord"),"41","48");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre des Cinq Rois", (select id_region from region where nom like "Westeros"),"298","302");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre des Premiers Hommes et des Enfants de la Forêt", (select id_region from region where nom like "Westeros"),"-12000","-10000");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre des Rois à Neuf Sous", (select id_region from region where nom like "Degrés de Pierre"),"259","259");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerre pour les Degrés de Pierre", (select id_region from region where nom like "Degrés de Pierre"),"106","115");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Guerres Ghiscaries", (select id_region from region where nom like "Péninsule valyrienne"),"-6000","-5000");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Intrigues d'entre-deux guerres", (select id_region from region where nom like "Westeros"),"302","304");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Invasion de Westeros par Daenerys Targaryen", (select id_region from region where nom like "Westeros"),"304","305");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Invasion des Andals", (select id_region from region where nom like "Westeros"),"-6000","-4000");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Libération de la Baie des Serfs", (select id_region from region where nom like "Baie des Serfs"),"300","303");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Longue Nuit", (select id_region from region where nom like "Westeros"),"-8000","-8000");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Première Guerre Dornienne", (select id_region from region where nom like "Principauté de Dorne"),"4","13");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Rébellion de Robert", (select id_region from region where nom like "Westeros"),"280","282");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Rébellion Feunoyr", (select id_region from region where nom like "Sept Couronnes"),"195","196");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Rébellion Greyjoy", (select id_region from region where nom like "Îles de Fer"),"289","289");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Rébellion Reyne", (select id_region from region where nom like "Terres de l'Ouest"),"260","260");
INSERT INTO Guerre (nom, id_lieu,annee_deb , annee_fin) values ("Unification du Nord", (select id_region from region where nom like "Nord"),"-8000","-6000");
